<?php

namespace CRM\PagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * opportunityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class opportunityRepository extends EntityRepository
{
}
